site_name: Metacentrum Documentation
docs_dir: docs
site_url: https://docs.metacentrum.cz

extra:
  generator: false
  version: !ENV [SITE_VERSION, 'undef_build_number']
  site_title: e-INFRA CZ Documentation

# custom stylesheet
extra_css:
  - stylesheets/metacentrum_custom.css

theme:
  name: material
  language: 'en'    
  features:
    - navigation.tabs
#    - navigation.sections
  font:
    text: 'Ubuntu'
    code: 'Source Code Pro'

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)'
      lang:
        - en
  - mkdocs-jupyter:
      ignore_h1_titles: True
      include_source: True

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets:
      base_path: docs/snippets
  - codehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Access:
    - access/terms.md
    - access/account.md
    - access/log-in.md
    - access/perun.md
    - access/pbsmon.md
    - access/elixir.md
    - 'Security':
      - access/connect-auth.md
      - access/kerberos.md
  - Computing:
    - computing/concepts.md
    - computing/run-basic-job.md
    - 'Jobs':
      - computing/jobs/job-tracking.md
      - computing/jobs/extend-walltime.md
      - computing/jobs/modify-job-attributes.md
      - computing/jobs/trap-command.md
      - computing/jobs/job-arrays.md
      - computing/jobs/finished-jobs.md
      - computing/jobs/email-notif.md
    - 'Infrastructure':
      - computing/infrastructure/frontends.md
      - computing/infrastructure/storages.md
      - computing/infrastructure/frontend-storage.md
      - computing/infrastructure/scratch-storages.md
      - computing/infrastructure/mount-storages.md
      - computing/infrastructure/specific-nodes.md
      - computing/infrastructure/decommissioned-storages.md
    - 'Resources and queues':
      - computing/resources/resources.md
      - computing/resources/pbs-commands.md
      - computing/resources/qsub-compiler.md
      - computing/resources/queues.md
      - computing/resources/fairshare.md
    - 'GPU computing':
      - computing/gpu-comput/gpu-job.md
      - computing/gpu-comput/clusters.md
      - computing/gpu-comput/nvidia.md
      - computing/gpu-comput/dgx.md
    - computing/parallel-comput.md
  - Data:
    - data/types-of-storage.md
    - data/large-data.md      
    - data/direct-access-storages.md
    - data/data-sharing.md
    - data/quotas.md
    - data/filesender.md
    - data/metacentrum-backup.md
    - data/storage-department.md
  - Software:
    - software/alphabet.md
    - 'Software sorted by field':
      - 'Chemistry':
         - software/sw-list/amber.md
         - software/sw-list/gaussian.md
         - software/sw-list/molden.md
         - software/sw-list/molpro.md
         - software/sw-list/turbomole.md
         - software/sw-list/vasp.md
         - software/sw-list/vmd.md
         - software/sw-list/wien2k.md
      - 'Genomics, proteomics':
         - software/sw-list/alphafold.md
         - software/sw-list/clcbio-genomics-wb.md
         - software/sw-list/geneious.md
      - 'Compilers, debuggers':
         - software/sw-list/allinea-ddt.md
         - software/sw-list/intel.md
         - software/sw-list/pgi-cdk.md
         - software/sw-list/rstudio.md
         - software/sw-list/total-view.md
      - 'Languages':
         - software/sw-list/r.md
         - software/sw-list/java.md
      - 'Mechanics':
         - software/sw-list/ansys.md
      - 'Mathematics':
         - software/sw-list/maple.md
         - software/sw-list/matlab.md
         - software/sw-list/wolfram-math.md   
    - software/search-soft.md
    - software/install-software.md
    - software/graphical-access.md
    - software/modules.md
    - software/containers.md
  - 'OnDemand':
    - ondemand/index.md
  - 'Support':
    - support/index.md
    - support/faqs.md
    - support/outages.md
    - support/contribute.md
  - Tutorials: tutorials/index.md
  - 'Related projects': 
    - related/galaxy/index.md
    - related/chipster/index.md
    - related/kubernetes/index.md
    - related/jupyter/index.md
    - 'CollGS': 
      - related/collgs/index.md
      - related/collgs/era5.md
      - related/collgs/pristup-k-datum.md
      - 'C-scale data discovery': related/notebooks/c-scale-notebooks/1-C-SCALE_Data_Discovery.ipynb
