site_name: Metacentrum Documentation
docs_dir: docs
site_url: https://docs.metacentrum.cz

extra:
  generator: false
  version: !ENV [SITE_VERSION, 'undef_build_number']
  site_title: e-INFRA CZ Documentation

# custom stylesheet
extra_css:
  - stylesheets/metacentrum_custom.css

theme:
  name: material
  language: 'en'    
  features:
    - navigation.tabs
#    - navigation.sections
  font:
    text: 'Ubuntu'
    code: 'Source Code Pro'

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)'
      lang:
        - en
  - mkdocs-jupyter:
      ignore_h1_titles: True
      include_source: True

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.snippets:
      base_path: 'docs/snippets'
  - codehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Access:
    - access/index.md
    - access/terms/index.md
    - access/account/index.md
    - access/log-in/index.md
    - access/perun/index.md
    - access/pbsmon/index.md
    - access/elixir/index.md
  - Basics:
    - basics/index.md
    - basics/concepts/index.md
    - basics/jobs/index.md
    - basics/frontends/index.md
  - Data:
    - data/index.md
    - data/data-within/index.md
    - data/data-outside/index.md
    - data/backup-archive/index.md
    - data/data-sharing/index.md
    - data/quotas/index.md
  - Software:
    - software/index.md
    - software/alphabet/index.md
    - 'Software sorted by field':
      - 'Chemistry':
         - software/sw-list/amber.md
         - software/sw-list/gaussian.md
         - software/sw-list/molden.md
         - software/sw-list/molpro.md
         - software/sw-list/turbomole.md
         - software/sw-list/vasp.md
         - software/sw-list/vmd.md
         - software/sw-list/wien2k.md
      - 'Genomics, proteomics':
         - software/sw-list/alphafold.md
         - software/sw-list/clcbio-genomics-wb.md
         - software/sw-list/geneious.md
      - 'Compilers, debuggers':
         - software/sw-list/allinea-ddt.md
         - software/sw-list/intel.md
         - software/sw-list/pgi-cdk.md
         - software/sw-list/rstudio.md
         - software/sw-list/total-view.md
      - 'Languages':
         - software/sw-list/r.md
         - software/sw-list/java.md
      - 'Mechanics':
         - software/sw-list/ansys.md
      - 'Mathematics':
         - software/sw-list/maple.md
         - software/sw-list/matlab.md
         - software/sw-list/wolfram-math.md   
    - software/search-soft/index.md
    - software/graphical-access/index.md
    - software/modules/index.md
    - software/containers/index.md
    - 'Managed services':
        - software/services/ondemand/index.md
        - software/services/kubernetes/index.md
        - software/services/galaxy/index.md
        - software/services/jupyter/index.md
    - software/install-software/index.md
      #    - 'Graphical software':
      #      - software/sw-list/rstudio.md
      #      - software/sw-list/ansys.md
      #      - software/sw-list/matlab.md
      #      - software/sw-list/vmd.md


      #      - software/sw-list/alphafold.md
  - 'Advanced':
    - advanced/index.md
    - 'Access and security':
      - advanced/connect-auth/index.md
      - advanced/kerberos/index.md
    - 'PBS and job planning':    
      - advanced/pbs-options/index.md
      - advanced/queues-in-meta/index.md
      - advanced/fairshare/index.md
    - 'Job state and history':
      - advanced/job-tracking/index.md
    - 'Infrastructure':  
      - advanced/grid-infrastruct/index.md
      - advanced/mount-storages/index.md
    - advanced/gpu-comput/index.md
    - advanced/parallel-comput/index.md
  - 'Troubleshooting':
    - troubleshooting/index.md
    - troubleshooting/faqs/index.md
    - troubleshooting/outages/index.md
    - troubleshooting/known-issues/index.md
  - 'User support':
    - contact/index.md
    - contact/write-request/index.md
  - Tutorials: tutorials/index.md
  - 'Jupyter notebooks': 
    - 'Notebook no. 1': jupyter-notebooks/c-scale-data-discovery.ipynb
