site_name: Metacentrum Documentation
docs_dir: docs
site_url: https://docs.metacentrum.cz

extra:
  generator: false
  version: !ENV [SITE_VERSION, 'undef_build_number']
  site_title: e-INFRA CZ Documentation

# custom stylesheet
extra_css:
  - stylesheets/metacentrum_custom.css

theme:
  name: material
  language: 'en'    
  features:
    - navigation.tabs
#    - navigation.sections
  font:
    text: 'Ubuntu'
    code: 'Source Code Pro'

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)'
      lang:
        - en
  - mkdocs-jupyter:
      ignore_h1_titles: True
      include_source: True

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets:
      base_path: docs/snippets
  - codehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Access:
    - access/index.md
    - access/terms/index.md
    - access/account/index.md
    - access/log-in/index.md
    - access/perun/index.md
    - access/pbsmon/index.md
    - access/elixir/index.md
    - 'Security':
      - access/connect-auth/index.md
      - access/kerberos/index.md
  - Computing:
    - computing/index.md
    - computing/concepts/index.md
    - computing/run-basic-job/index.md
    - 'Jobs':
      - computing/job-tracking/index.md
      - computing/extend-walltime/index.md
      - computing/trap-command/index.md
      - computing/job-arrays/index.md
      - computing/finished-jobs/index.md
      - computing/email-notif/index.md
    - 'Infrastructure':
      - computing/frontends/index.md
      - computing/storages/index.md
      - computing/frontend-storage/index.md
      - computing/scratch-storages/index.md
      - computing/mount-storages/index.md
      - computing/node-properties/index.md
      - computing/decommissioned-storages/index.md
    - 'Resources and queues':
      - computing/pbs-resources/index.md
      - computing/pbs-commands/index.md
      - computing/qsub-compiler/index.md
      - computing/queues-in-meta/index.md
      - computing/fairshare/index.md
    - 'GPU computing':
      - computing/gpu-comput/index.md
      - computing/nvidia-gpu/index.md
      - computing/gpu-clusters/index.md
    - computing/parallel-comput/index.md
  - Data:
    - data/index.md
    - data/useful-commands/index.md
    - data/large-data/index.md      
    - data/direct-access-storages/index.md
    - data/data-sharing/index.md
    - data/quotas/index.md
    - data/filesender/index.md
    - data/metacentrum-backup/index.md
    - data/storage-department/index.md
  - Software:
    - software/index.md
    - software/alphabet/index.md
    - 'Software sorted by field':
      - 'Chemistry':
         - software/sw-list/amber.md
         - software/sw-list/gaussian.md
         - software/sw-list/molden.md
         - software/sw-list/molpro.md
         - software/sw-list/turbomole.md
         - software/sw-list/vasp.md
         - software/sw-list/vmd.md
         - software/sw-list/wien2k.md
      - 'Genomics, proteomics':
         - software/sw-list/alphafold.md
         - software/sw-list/clcbio-genomics-wb.md
         - software/sw-list/geneious.md
      - 'Compilers, debuggers':
         - software/sw-list/allinea-ddt.md
         - software/sw-list/intel.md
         - software/sw-list/pgi-cdk.md
         - software/sw-list/rstudio.md
         - software/sw-list/total-view.md
      - 'Languages':
         - software/sw-list/r.md
         - software/sw-list/java.md
      - 'Mechanics':
         - software/sw-list/ansys.md
      - 'Mathematics':
         - software/sw-list/maple.md
         - software/sw-list/matlab.md
         - software/sw-list/wolfram-math.md   
    - software/search-soft/index.md
    - software/graphical-access/index.md
    - software/ondemand/index.md
    - software/modules/index.md
    - software/containers/index.md
    - software/install-software/index.md
  - 'Troubleshooting':
    - troubleshooting/index.md
    - troubleshooting/faqs/index.md
    - troubleshooting/outages/index.md
    - troubleshooting/known-issues/index.md
  - 'User support':
    - contact/index.md
    - contact/write-request/index.md
  - Tutorials: tutorials/index.md
  - 'Related projects': 
    - related/galaxy/index.md
    - related/chipster/index.md
    - related/kubernetes/index.md
    - 'CollGS': 
      - related/collgs/index.md
      - related/collgs/era5.md
      - related/collgs/pristup-k-datum.md
    - related/jupyter/index.md
    - related/notebooks/c-scale-data-discovery.ipynb
